name: 每日IP提取

on:
  schedule:
    - cron: '0 22 * * *'  # 每天UTC时间的06:00启动（对应北京时间14:00）
  workflow_dispatch:  # 手动触发

jobs:
  extract_ips:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 设置git用户信息
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: 创建ip目录
        run: mkdir -p ip
      
      - name: 列出模板文件
        id: list_files
        run: |
          ls template/*.txt | xargs -n 1 basename > files.txt

      - name: 从模板文件提取IP地址
        id: extract_ips
        run: |
          while IFS= read -r filename; do
            url="https://raw.githubusercontent.com/redrainl/iptv/main/speedtest/result/result_$filename"
            content=$(curl -sSL "$url")
            if [ -n "$content" ] && ! echo "$content" | grep -q "404: Not Found"; then
              echo "$content" | awk '{print $2}' >> "ip/$filename"
            fi
          done < files.txt

      - name: 提交更改
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用个人访问令牌（PAT）进行推送
        run: |
          git add ip/*.txt
          git commit -m "更新IP列表"
          git push --set-upstream origin $GITHUB_REF
