name: Daily IP Collection

on:
  schedule:
    - cron: '0 22 * * *'  # 北京时间每天早上6点执行
  workflow_dispatch:  # 手动触发

permissions:
  contents: write
  
jobs:
  collect_ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create IP directory
        run: mkdir -p ip

      - name: List template files
        id: list_files
        run: |
          echo "::set-output name=files::$(ls template/*.txt)"

      - name: Extract IPs from template files
        run: |
          files="${{ steps.list_files.outputs.files }}"
          for file in $files; do
            filename=$(basename $file .txt)
            echo "Processing file: $filename"
            curl -sSL "https://raw.githubusercontent.com/redrainl/iptv/main/speedtest/result/result_${filename}.txt" | awk '{print $2}' > "ip/${filename}.txt"
            cat "ip/${filename}.txt"  # 输出文件内容以便调试
          done

      - name: Configure Git
        env:
          PAT: ${{ secrets.GITHUBS_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Add files to Git
        run: |
          git add ip/*.txt
          
      - name: Check Git status
        run: |
          git status
          
      - name: Commit changes
        run: |
          git commit -m "Update IP files" || echo "Nothing to commit"
          
      - name: Push changes
        run: |
          git push origin HEAD || echo "Push failed"
