name: Daily IP Collection

on:
  schedule:
    - cron: '0 22 * * *'  # 北京时间每天早上6点执行
  workflow_dispatch:  # 手动触发

jobs:
  collect_ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create IP directory
        run: mkdir -p ip

      - name: List template files
        id: list_files
        run: |
          echo "::set-output name=files::$(ls template/*.txt)"

      - name: Extract IPs from template files
        run: |
          for file in ${{ steps.list_files.outputs.files }}; do
            filename=$(basename $file .txt)
            curl -sSL "https://raw.githubusercontent.com/redrainl/iptv/main/speedtest/result/result_${filename}.txt" | awk '{print $2}' > "ip/${filename}.txt"
          done

      - name: Configure Git
        env:
          PAT: ${{ secrets.GITHUBS_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.GITHUBS_TOKEN }}
        run: |
          git add ip/*.txt
          git commit -m "Update IP files"
          git push origin HEAD
