name: creat
on:
schedule:
- cron: "0 6 * * *"
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v2

- name: Get filenames
    id: filenames
    run: |
      FILES=$(ls -1 template | grep ".txt")
      echo "##[set-output name=filenames;]${FILES}"

  - name: Process files
    run: |
      for filename in ${{ steps.filenames.outputs.filenames }}
      do
        echo "Processing $filename"
        url="https://raw.githubusercontent.com/redrainl/iptv/main/speedtest/result/$filename"
        while IFS= read -r line; do
          IPPORT=$(echo $line | awk '{print $2}')
          echo $IPPORT >> ip/$filename
        done < <(curl -s "$url")  
      done
