name: Fetch IP Addresses
on:
  schedule:
    - cron: '0 22 * * *'  # Beijing time 06:00 UTC is 14:00 UTC, so 22:00 UTC the previous day
  workflow_dispatch:

jobs:
  fetch_ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List templates
        id: list_templates
        run: |
          templates=$(ls template/*.txt)
          echo "::set-output name=templates::$templates"

      - name: Generate IP URLs
        id: generate_urls
        run: |
          templates="$INPUT_TEMPLATES"
          urls=""
          for template in $templates; do
            filename=$(basename "$template")
            region=${filename%.*}
            urls+="https://raw.githubusercontent.com/redrainl/iptv/main/speedtest/result/result_${region}.txt\n"
          done
          echo "::set-output name=urls::$urls"

      - name: Fetch and process IPs
        id: fetch_ips
        run: |
          urls="$INPUT_URLS"
          while IFS= read -r url; do
            content=$(curl -sSL "$url")
            echo "$content" | grep -oP '\S+:\d+' >> ip/hebei.txt
          done <<< "$urls"
        env:
          INPUT_URLS: ${{ steps.generate_urls.outputs.urls }}
          INPUT_TEMPLATES: ${{ steps.list_templates.outputs.templates }}
