name: EPG Update
on:
  #push:
  #schedule:
    #- cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'
  workflow_dispatch:  # 手动触发  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update EPG Files
      run: |
        rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O e.xml
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add e.xml
        git commit -m "EPG Automatic Update."
    - name: Push changes
      run: git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN  }}

    - name: xml to json
      working-directory: epg
      run: |
        mkdir ./xml ./json
        mv -f ../e.xml ./xml/e.xml
        pip3 install xmltodict
        python3 epg/xml2json.py
