name: Run Process Templates

on:
  schedule:
    - cron: '0 22 * * *'  # 北京时间每天早上6点执行
  workflow_dispatch:  # 手动触发

permissions:
  contents: write

jobs:
  update_templates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果需要特定的依赖包，请在 requirements.txt 中列出

    - name: Execute Python script
      run: python process_templates.py
