name: Run Process Templates

on:
  schedule:
    - cron: '0 22 * * *'  # 北京时间每天早上6点执行
  workflow_dispatch:  # 手动触发

permissions:
  contents: write

jobs:
  update_templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # 指定 PHP 版本，根据您的需求选择适当的版本

      - name: List directory contents
        run: |
          echo "Listing root directory"
          ls -R
          echo "Listing ip directory"
          ls -R ip
          echo "Listing template directory"
          ls -R template
          echo "Listing result directory (should be empty initially)"
          ls -R result || echo "result directory is empty"

      - name: Execute PHP script
        run: php update_templates.php

      - name: List result directory contents
        run: |
          echo "Listing result directory after script execution"
          ls -R result
